- hosts: webservers

  tasks:
    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
      become: yes
      tags: install

    - name: update_cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes
      tags: apt
